<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>koma</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Koma.Cli.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Koma.Core\Koma.Core.csproj" />
    <ProjectReference Include="..\Koma.Imaging\Koma.Imaging.csproj" />
  </ItemGroup>

</Project>
