#!/usr/bin/env python3
"""Generate CaseFoldingTable.cs from the Unicode data Python carries.

3 of the specification requires logical entry names to be unique after NFC
normalization and full case folding. .NET exposes no case folding at all, and
its ToUpperInvariant and ToLowerInvariant implement the simple case mappings,
which differ: they leave the German sharp s alone where full folding expands it
to "ss".

The table is generated rather than written by hand, and it is generated from
str.casefold, which is the same function tools/check_corpus.py uses in the
specification repository. Running this with the same Python that runs the
reference validator is what makes the two implementations agree.

If unidata_version below differs from the one recorded in the generated file,
regenerate it: a Unicode release can add mappings, and the two sides must be
built from the same one.

Usage:
    python tools/generate_case_folding.py > src/Koma.Core/Packaging/CaseFoldingTable.cs
"""

import sys
import unicodedata

HEADER = '''// <auto-generated>
//     Generated by tools/generate_case_folding.py from Unicode {version}.
//     Do not edit. Regenerate instead, with the same Python that runs the
//     reference validator of the specification repository.
// </auto-generated>

namespace Koma.Core.Packaging;

/// <summary>
/// Unicode full case folding, as 3 requires for logical name uniqueness.
/// </summary>
/// <remarks>
/// <para>
/// .NET offers no case folding. Its ToUpperInvariant and ToLowerInvariant
/// implement the simple case mappings, which are not the same thing: they map
/// one code point to one code point, so the German sharp s survives where full
/// folding turns it into two characters. A reader built on them accepts a
/// package the reference validator rejects.
/// </para>
/// <para>
/// Carrying the whole table rather than folding on top of the runtime's casing
/// also pins the behaviour to a Unicode version we choose. Otherwise the same
/// build would fold differently depending on the ICU shipped with the host,
/// which is not a property a conformance claim can survive.
/// </para>
/// </remarks>
internal static class CaseFoldingTable
{{
    /// <summary>The Unicode release these mappings were generated from.</summary>
    internal const string UnicodeVersion = "{version}";

    /// <summary>Code points with a folding, ascending, for binary search.</summary>
    internal static readonly int[] Keys =
    [
'''

FOOTER = '''    ];
}
'''


def escape(s):
    """C# string literal, ASCII only so the file has no encoding of its own."""
    out = []
    for ch in s:
        if " " <= ch <= "~" and ch not in '"\\':
            out.append(ch)
        elif ord(ch) > 0xFFFF:
            # C# spells astral code points with eight digits, not five.
            out.append(f"\\U{ord(ch):08X}")
        else:
            out.append(f"\\u{ord(ch):04X}")
    return '"' + "".join(out) + '"'


def main():
    folds = {c: chr(c).casefold()
             for c in range(0x110000)
             if chr(c).casefold() != chr(c)}
    keys = sorted(folds)

    out = sys.stdout
    out.write(HEADER.format(version=unicodedata.unidata_version))

    for i in range(0, len(keys), 8):
        row = ", ".join(f"0x{k:04X}" for k in keys[i:i + 8])
        out.write(f"        {row},\n")

    out.write("    ];\n\n")
    out.write("    /// <summary>Folded form of each key, in the same order.</summary>\n")
    out.write("    internal static readonly string[] Values =\n    [\n")

    for i in range(0, len(keys), 6):
        row = ", ".join(escape(folds[k]) for k in keys[i:i + 6])
        out.write(f"        {row},\n")

    out.write(FOOTER)


if __name__ == "__main__":
    main()
